/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Tab;

import Model.Book.Book;
import Model.Book.BookDao;
import java.awt.Color;

/**
 *
 * @author nhaantran
 */
public class InsertBook extends javax.swing.JPanel {

    /**
     * Creates new form InsertBook
     */
    public InsertBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        insertbookpane1 = new javax.swing.JPanel();
        lblinsertname = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        lblinsertname1 = new javax.swing.JLabel();
        txtreleasedate = new javax.swing.JTextField();
        lblinsertname2 = new javax.swing.JLabel();
        txtedition = new javax.swing.JTextField();
        lblinsertname12 = new javax.swing.JLabel();
        txtnumpages = new javax.swing.JTextField();
        lblinsertname13 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        insertbookpane2 = new javax.swing.JPanel();
        lblinsertname7 = new javax.swing.JLabel();
        lblinsertname4 = new javax.swing.JLabel();
        lblinsertname5 = new javax.swing.JLabel();
        lblinsertname6 = new javax.swing.JLabel();
        lblinsertname11 = new javax.swing.JLabel();
        txtsupplier = new javax.swing.JTextField();
        txtbookcover = new javax.swing.JTextField();
        txtauthor = new javax.swing.JTextField();
        txttype = new javax.swing.JTextField();
        txtpublisher = new javax.swing.JTextField();
        insertbookpane3 = new javax.swing.JPanel();
        btnadd = new javax.swing.JButton();
        lblinsertname3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdescription = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        insertbookpane1.setBackground(new java.awt.Color(255, 255, 255));

        lblinsertname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblinsertname.setForeground(new java.awt.Color(0, 0, 0));
        lblinsertname.setText("Name:");

        txtname.setForeground(new java.awt.Color(153, 153, 153));
        txtname.setText("Enter Name");
        txtname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnameFocusLost(evt);
            }
        });
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        lblinsertname1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblinsertname1.setForeground(new java.awt.Color(0, 0, 0));
        lblinsertname1.setText("ReleaseDate");

        txtreleasedate.setForeground(new java.awt.Color(153, 153, 153));
        txtreleasedate.setText("Enter ReleaseDate");
        txtreleasedate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtreleasedateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtreleasedateFocusLost(evt);
            }
        });

        lblinsertname2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblinsertname2.setForeground(new java.awt.Color(0, 0, 0));
        lblinsertname2.setText("Edition");

        txtedition.setForeground(new java.awt.Color(153, 153, 153));
        txtedition.setText("Enter Edition");
        txtedition.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txteditionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txteditionFocusLost(evt);
            }
        });

        lblinsertname12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblinsertname12.setForeground(new java.awt.Color(0, 0, 0));
        lblinsertname12.setText("NumPages:");

        txtnumpages.setForeground(new java.awt.Color(153, 153, 153));
        txtnumpages.setText("Enter NumPages");
        txtnumpages.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnumpagesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnumpagesFocusLost(evt);
            }
        });

        lblinsertname13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblinsertname13.setForeground(new java.awt.Color(0, 0, 0));
        lblinsertname13.setText("Price:");

        txtprice.setForeground(new java.awt.Color(153, 153, 153));
        txtprice.setText("Enter Price");
        txtprice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpriceFocusLost(evt);
            }
        });

        javax.swing.GroupLayout insertbookpane1Layout = new javax.swing.GroupLayout(insertbookpane1);
        insertbookpane1.setLayout(insertbookpane1Layout);
        insertbookpane1Layout.setHorizontalGroup(
            insertbookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertbookpane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(insertbookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insertbookpane1Layout.createSequentialGroup()
                        .addGroup(insertbookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblinsertname, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblinsertname1))
                        .addGap(57, 57, 57)
                        .addGroup(insertbookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtreleasedate)
                            .addComponent(txtname)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insertbookpane1Layout.createSequentialGroup()
                        .addGroup(insertbookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblinsertname12)
                            .addComponent(lblinsertname13)
                            .addComponent(lblinsertname2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(insertbookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtprice)
                            .addComponent(txtnumpages, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(txtedition, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        insertbookpane1Layout.setVerticalGroup(
            insertbookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertbookpane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(insertbookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblinsertname)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(insertbookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblinsertname1)
                    .addComponent(txtreleasedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(insertbookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblinsertname2)
                    .addComponent(txtedition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(insertbookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblinsertname12)
                    .addComponent(txtnumpages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(insertbookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblinsertname13)
                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        insertbookpane2.setBackground(new java.awt.Color(255, 255, 255));

        lblinsertname7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblinsertname7.setForeground(new java.awt.Color(0, 0, 0));
        lblinsertname7.setText("Supplier:");

        lblinsertname4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblinsertname4.setForeground(new java.awt.Color(0, 0, 0));
        lblinsertname4.setText("BookCover:");

        lblinsertname5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblinsertname5.setForeground(new java.awt.Color(0, 0, 0));
        lblinsertname5.setText("Author:");

        lblinsertname6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblinsertname6.setForeground(new java.awt.Color(0, 0, 0));
        lblinsertname6.setText("Type:");

        lblinsertname11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblinsertname11.setForeground(new java.awt.Color(0, 0, 0));
        lblinsertname11.setText("Publisher:");

        txtsupplier.setForeground(new java.awt.Color(153, 153, 153));
        txtsupplier.setText("Enter Supplier");
        txtsupplier.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtsupplierFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtsupplierFocusLost(evt);
            }
        });

        txtbookcover.setForeground(new java.awt.Color(153, 153, 153));
        txtbookcover.setText("Enter BookCover");
        txtbookcover.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtbookcoverFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtbookcoverFocusLost(evt);
            }
        });

        txtauthor.setForeground(new java.awt.Color(153, 153, 153));
        txtauthor.setText("Enter Author");
        txtauthor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtauthorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtauthorFocusLost(evt);
            }
        });

        txttype.setForeground(new java.awt.Color(153, 153, 153));
        txttype.setText("Enter Type");
        txttype.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txttypeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttypeFocusLost(evt);
            }
        });

        txtpublisher.setForeground(new java.awt.Color(153, 153, 153));
        txtpublisher.setText("Enter Publisher");
        txtpublisher.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpublisherFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpublisherFocusLost(evt);
            }
        });

        javax.swing.GroupLayout insertbookpane2Layout = new javax.swing.GroupLayout(insertbookpane2);
        insertbookpane2.setLayout(insertbookpane2Layout);
        insertbookpane2Layout.setHorizontalGroup(
            insertbookpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertbookpane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(insertbookpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblinsertname4)
                    .addComponent(lblinsertname11)
                    .addComponent(lblinsertname6)
                    .addComponent(lblinsertname5)
                    .addComponent(lblinsertname7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(insertbookpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtsupplier)
                    .addComponent(txtbookcover)
                    .addComponent(txtauthor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txttype, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtpublisher, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        insertbookpane2Layout.setVerticalGroup(
            insertbookpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertbookpane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(insertbookpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblinsertname7)
                    .addComponent(txtsupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(insertbookpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblinsertname4)
                    .addComponent(txtbookcover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(insertbookpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblinsertname5)
                    .addComponent(txtauthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(insertbookpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblinsertname6)
                    .addComponent(txttype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(insertbookpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblinsertname11)
                    .addComponent(txtpublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        insertbookpane3.setBackground(new java.awt.Color(255, 255, 255));

        btnadd.setBackground(new java.awt.Color(0, 153, 255));
        btnadd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnadd.setForeground(new java.awt.Color(255, 255, 255));
        btnadd.setText("Add Book");
        btnadd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        lblinsertname3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblinsertname3.setForeground(new java.awt.Color(0, 0, 0));
        lblinsertname3.setText("Description");

        txtdescription.setColumns(20);
        txtdescription.setLineWrap(true);
        txtdescription.setRows(5);
        jScrollPane1.setViewportView(txtdescription);

        javax.swing.GroupLayout insertbookpane3Layout = new javax.swing.GroupLayout(insertbookpane3);
        insertbookpane3.setLayout(insertbookpane3Layout);
        insertbookpane3Layout.setHorizontalGroup(
            insertbookpane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insertbookpane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblinsertname3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(insertbookpane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                .addContainerGap())
        );
        insertbookpane3Layout.setVerticalGroup(
            insertbookpane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertbookpane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(insertbookpane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblinsertname3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnadd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(insertbookpane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(insertbookpane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(insertbookpane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(insertbookpane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(insertbookpane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(insertbookpane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnameFocusGained
        // TODO add your handling code here:
        if(txtname.getText().equals("Enter Name")){
            txtname.setText("");
            txtname.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtnameFocusGained

    private void txtnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnameFocusLost
        // TODO add your handling code here:
        if(txtname.getText().equals("")){
            txtname.setText("Enter Name");
            txtname.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtnameFocusLost

    private void txtreleasedateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtreleasedateFocusGained
        // TODO add your handling code here:
        if(txtreleasedate.getText().equals("Enter ReleaseDate")){
            txtreleasedate.setText("");
            txtreleasedate.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtreleasedateFocusGained

    private void txtreleasedateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtreleasedateFocusLost
        // TODO add your handling code here:
        if(txtreleasedate.getText().equals("")){
            txtreleasedate.setText("Enter ReleaseDate");
            txtreleasedate.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtreleasedateFocusLost

    private void txteditionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txteditionFocusGained
        // TODO add your handling code here:
        if(txtedition.getText().equals("Enter Edition")){
            txtedition.setText("");
            txtedition.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txteditionFocusGained

    private void txteditionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txteditionFocusLost
        // TODO add your handling code here:
        if(txtedition.getText().equals("")){
            txtedition.setText("Enter Edition");
            txtedition.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txteditionFocusLost

    private void txtnumpagesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnumpagesFocusGained
        // TODO add your handling code here:
        if(txtnumpages.getText().equals("Enter NumPages")){
            txtnumpages.setText("");
            txtnumpages.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtnumpagesFocusGained

    private void txtnumpagesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnumpagesFocusLost
        // TODO add your handling code here:
        if(txtnumpages.getText().equals("")){
            txtnumpages.setText("Enter NumPages");
            txtnumpages.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtnumpagesFocusLost

    private void txtpriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpriceFocusGained
        // TODO add your handling code here:
        if(txtprice.getText().equals("Enter Price")){
            txtprice.setText("");
            txtprice.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtpriceFocusGained

    private void txtpriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpriceFocusLost
        // TODO add your handling code here:
        if(txtprice.getText().equals("")){
            txtprice.setText("Enter Price");
            txtprice.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtpriceFocusLost

    private void txtsupplierFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsupplierFocusGained
        // TODO add your handling code here:
        if(txtsupplier.getText().equals("Enter Supplier")){
            txtsupplier.setText("");
            txtsupplier.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtsupplierFocusGained

    private void txtsupplierFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsupplierFocusLost
        // TODO add your handling code here:
        if(txtsupplier.getText().equals("")){
            txtsupplier.setText("Enter Supplier");
            txtsupplier.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtsupplierFocusLost

    private void txtbookcoverFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtbookcoverFocusGained
        // TODO add your handling code here:
        if(txtbookcover.getText().equals("Enter BookCover")){
            txtbookcover.setText("");
            txtbookcover.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtbookcoverFocusGained

    private void txtbookcoverFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtbookcoverFocusLost
        // TODO add your handling code here:
        if(txtbookcover.getText().equals("")){
            txtbookcover.setText("Enter BookCover");
            txtbookcover.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtbookcoverFocusLost

    private void txtauthorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtauthorFocusGained
        // TODO add your handling code here:
        if(txtauthor.getText().equals("Enter Author")){
            txtauthor.setText("");
            txtauthor.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtauthorFocusGained

    private void txtauthorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtauthorFocusLost
        // TODO add your handling code here:
        if(txtauthor.getText().equals("")){
            txtauthor.setText("Enter Author");
            txtauthor.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtauthorFocusLost

    private void txttypeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttypeFocusGained
        // TODO add your handling code here:
        if(txttype.getText().equals("Enter Type")){
            txttype.setText("");
            txttype.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txttypeFocusGained

    private void txttypeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttypeFocusLost
        // TODO add your handling code here:
        if(txttype.getText().equals("")){
            txttype.setText("Enter Type");
            txttype.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txttypeFocusLost

    private void txtpublisherFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpublisherFocusGained
        // TODO add your handling code here:
        if(txtpublisher.getText().equals("Enter Publisher")){
            txtpublisher.setText("");
            txtpublisher.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtpublisherFocusGained

    private void txtpublisherFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpublisherFocusLost
        // TODO add your handling code here:
        if(txtpublisher.getText().equals("")){
            txtpublisher.setText("Enter Publisher");
            txtpublisher.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtpublisherFocusLost

    BookDao std = new BookDao();
    Book book = new Book();
    
    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        book.setName(txtname.getText());
        book.setReleaseDate(txtreleasedate.getText());
        book.setDescription(txtdescription.getText());
        book.setEdition(Float.valueOf(txtedition.getText()));
        book.setNumPages(Integer.valueOf(txtnumpages.getText()));
        book.setPrice(Double.valueOf(txtprice.getText()));
        book.setSupplier(txtsupplier.getText());
        book.setAuthor(txtauthor.getText());
        book.setPublisher(txtpublisher.getText());
        book.setType(txttype.getText());
        book.setBookCover(txtbookcover.getText());
        std.add(book);
    }//GEN-LAST:event_btnaddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JPanel insertbookpane1;
    private javax.swing.JPanel insertbookpane2;
    private javax.swing.JPanel insertbookpane3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblinsertname;
    private javax.swing.JLabel lblinsertname1;
    private javax.swing.JLabel lblinsertname11;
    private javax.swing.JLabel lblinsertname12;
    private javax.swing.JLabel lblinsertname13;
    private javax.swing.JLabel lblinsertname2;
    private javax.swing.JLabel lblinsertname3;
    private javax.swing.JLabel lblinsertname4;
    private javax.swing.JLabel lblinsertname5;
    private javax.swing.JLabel lblinsertname6;
    private javax.swing.JLabel lblinsertname7;
    private javax.swing.JTextField txtauthor;
    private javax.swing.JTextField txtbookcover;
    private javax.swing.JTextArea txtdescription;
    private javax.swing.JTextField txtedition;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnumpages;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtpublisher;
    private javax.swing.JTextField txtreleasedate;
    private javax.swing.JTextField txtsupplier;
    private javax.swing.JTextField txttype;
    // End of variables declaration//GEN-END:variables
}
