/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View.Tab;

import Model.Book.Book;
import Model.Book.BookDao;
import java.awt.Color;

/**
 *
 * @author nhaantran
 */
public class UpdateBook extends javax.swing.JDialog {

    /**
     * Creates new form test
     */
    
    private Book bk;
    public UpdateBook(java.awt.Frame parent, Book bk) {
        super(parent);
        initComponents();
        this.setTitle("Update Book");
        this.setLocationRelativeTo(null);
        this.bk = new Book();
        this.bk = bk;
        System.out.println("Create: "+this.bk.getID());
        txtid.setText(bk.getID());
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        updatebookpane1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rdbtnname = new javax.swing.JRadioButton();
        rdbtnamount = new javax.swing.JRadioButton();
        rdbtnreleasedate = new javax.swing.JRadioButton();
        rdbtnnumpages = new javax.swing.JRadioButton();
        rdbtnprice = new javax.swing.JRadioButton();
        txtid = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtamount = new javax.swing.JTextField();
        txtreleasedate = new javax.swing.JTextField();
        txtnumpages = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        updatebookpane2 = new javax.swing.JPanel();
        rdbtnpublisher = new javax.swing.JRadioButton();
        rdbtnsupplier = new javax.swing.JRadioButton();
        rdbtnauthor = new javax.swing.JRadioButton();
        rdbtnbookcover = new javax.swing.JRadioButton();
        rdbtntype = new javax.swing.JRadioButton();
        txtpublisher = new javax.swing.JTextField();
        txtsupplier = new javax.swing.JTextField();
        txtauthor = new javax.swing.JTextField();
        txtbookcover = new javax.swing.JTextField();
        txttype = new javax.swing.JTextField();
        rdbtnedition = new javax.swing.JRadioButton();
        txtedition = new javax.swing.JTextField();
        updatebookpane3 = new javax.swing.JPanel();
        rdbtndescription = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdescription = new javax.swing.JTextArea();
        btnupdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(200, 400));

        updatebookpane1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Input ID:");

        rdbtnname.setForeground(new java.awt.Color(0, 0, 0));
        rdbtnname.setText("Name");
        rdbtnname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnnameActionPerformed(evt);
            }
        });

        rdbtnamount.setForeground(new java.awt.Color(0, 0, 0));
        rdbtnamount.setText("Amount");
        rdbtnamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnamountActionPerformed(evt);
            }
        });

        rdbtnreleasedate.setForeground(new java.awt.Color(0, 0, 0));
        rdbtnreleasedate.setText("Year");
        rdbtnreleasedate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnreleasedateActionPerformed(evt);
            }
        });

        rdbtnnumpages.setForeground(new java.awt.Color(0, 0, 0));
        rdbtnnumpages.setText("NumPages");
        rdbtnnumpages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnnumpagesActionPerformed(evt);
            }
        });

        rdbtnprice.setForeground(new java.awt.Color(0, 0, 0));
        rdbtnprice.setText("Price");
        rdbtnprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnpriceActionPerformed(evt);
            }
        });

        txtid.setForeground(new java.awt.Color(153, 153, 153));
        txtid.setText("Enter ID");
        txtid.setEnabled(false);
        txtid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtidFocusLost(evt);
            }
        });

        txtname.setForeground(new java.awt.Color(153, 153, 153));
        txtname.setText("Enter Name");
        txtname.setEnabled(false);
        txtname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnameFocusLost(evt);
            }
        });

        txtamount.setForeground(new java.awt.Color(153, 153, 153));
        txtamount.setText("Enter Amount");
        txtamount.setEnabled(false);
        txtamount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtamountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtamountFocusLost(evt);
            }
        });

        txtreleasedate.setForeground(new java.awt.Color(153, 153, 153));
        txtreleasedate.setText("Enter ReleaseDate");
        txtreleasedate.setEnabled(false);
        txtreleasedate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtreleasedateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtreleasedateFocusLost(evt);
            }
        });

        txtnumpages.setForeground(new java.awt.Color(153, 153, 153));
        txtnumpages.setText("Enter NumPages");
        txtnumpages.setEnabled(false);
        txtnumpages.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnumpagesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnumpagesFocusLost(evt);
            }
        });

        txtprice.setForeground(new java.awt.Color(153, 153, 153));
        txtprice.setText("Enter Price");
        txtprice.setEnabled(false);
        txtprice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpriceFocusLost(evt);
            }
        });

        javax.swing.GroupLayout updatebookpane1Layout = new javax.swing.GroupLayout(updatebookpane1);
        updatebookpane1.setLayout(updatebookpane1Layout);
        updatebookpane1Layout.setHorizontalGroup(
            updatebookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatebookpane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updatebookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbtnnumpages)
                    .addComponent(rdbtnprice)
                    .addComponent(rdbtnreleasedate)
                    .addComponent(rdbtnamount)
                    .addComponent(rdbtnname)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(updatebookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtid)
                    .addComponent(txtname)
                    .addComponent(txtamount)
                    .addComponent(txtreleasedate)
                    .addComponent(txtprice)
                    .addComponent(txtnumpages))
                .addContainerGap())
        );
        updatebookpane1Layout.setVerticalGroup(
            updatebookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatebookpane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updatebookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updatebookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbtnname)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updatebookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbtnamount)
                    .addComponent(txtamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updatebookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbtnreleasedate)
                    .addComponent(txtreleasedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updatebookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbtnnumpages)
                    .addComponent(txtnumpages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updatebookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbtnprice)
                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        updatebookpane2.setBackground(new java.awt.Color(255, 255, 255));

        rdbtnpublisher.setForeground(new java.awt.Color(0, 0, 0));
        rdbtnpublisher.setText("Publisher");
        rdbtnpublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnpublisherActionPerformed(evt);
            }
        });

        rdbtnsupplier.setForeground(new java.awt.Color(0, 0, 0));
        rdbtnsupplier.setText("Supplier");
        rdbtnsupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnsupplierActionPerformed(evt);
            }
        });

        rdbtnauthor.setForeground(new java.awt.Color(0, 0, 0));
        rdbtnauthor.setText("Author");
        rdbtnauthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnauthorActionPerformed(evt);
            }
        });

        rdbtnbookcover.setForeground(new java.awt.Color(0, 0, 0));
        rdbtnbookcover.setText("BookCover");
        rdbtnbookcover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnbookcoverActionPerformed(evt);
            }
        });

        rdbtntype.setForeground(new java.awt.Color(0, 0, 0));
        rdbtntype.setText("Type");
        rdbtntype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtntypeActionPerformed(evt);
            }
        });

        txtpublisher.setBackground(new java.awt.Color(255, 255, 255));
        txtpublisher.setForeground(new java.awt.Color(153, 153, 153));
        txtpublisher.setText("Enter Publisher");
        txtpublisher.setEnabled(false);
        txtpublisher.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpublisherFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpublisherFocusLost(evt);
            }
        });

        txtsupplier.setBackground(new java.awt.Color(255, 255, 255));
        txtsupplier.setForeground(new java.awt.Color(153, 153, 153));
        txtsupplier.setText("Enter Supplier");
        txtsupplier.setEnabled(false);
        txtsupplier.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtsupplierFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtsupplierFocusLost(evt);
            }
        });

        txtauthor.setBackground(new java.awt.Color(255, 255, 255));
        txtauthor.setForeground(new java.awt.Color(153, 153, 153));
        txtauthor.setText("Enter Author");
        txtauthor.setEnabled(false);
        txtauthor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtauthorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtauthorFocusLost(evt);
            }
        });

        txtbookcover.setBackground(new java.awt.Color(255, 255, 255));
        txtbookcover.setForeground(new java.awt.Color(153, 153, 153));
        txtbookcover.setText("Enter Author");
        txtbookcover.setEnabled(false);
        txtbookcover.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtbookcoverFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtbookcoverFocusLost(evt);
            }
        });

        txttype.setBackground(new java.awt.Color(255, 255, 255));
        txttype.setForeground(new java.awt.Color(153, 153, 153));
        txttype.setText("Enter Type");
        txttype.setEnabled(false);
        txttype.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txttypeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttypeFocusLost(evt);
            }
        });

        rdbtnedition.setForeground(new java.awt.Color(0, 0, 0));
        rdbtnedition.setText("Edition");
        rdbtnedition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtneditionActionPerformed(evt);
            }
        });

        txtedition.setBackground(new java.awt.Color(255, 255, 255));
        txtedition.setForeground(new java.awt.Color(153, 153, 153));
        txtedition.setText("Enter Edition");
        txtedition.setEnabled(false);
        txtedition.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txteditionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txteditionFocusLost(evt);
            }
        });

        javax.swing.GroupLayout updatebookpane2Layout = new javax.swing.GroupLayout(updatebookpane2);
        updatebookpane2.setLayout(updatebookpane2Layout);
        updatebookpane2Layout.setHorizontalGroup(
            updatebookpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatebookpane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updatebookpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbtnpublisher)
                    .addComponent(rdbtnsupplier)
                    .addComponent(rdbtnauthor)
                    .addComponent(rdbtnbookcover)
                    .addComponent(rdbtntype)
                    .addComponent(rdbtnedition))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(updatebookpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtedition)
                    .addGroup(updatebookpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txttype)
                        .addComponent(txtbookcover)
                        .addComponent(txtauthor)
                        .addComponent(txtsupplier)
                        .addComponent(txtpublisher)))
                .addContainerGap())
        );
        updatebookpane2Layout.setVerticalGroup(
            updatebookpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatebookpane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updatebookpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbtnpublisher)
                    .addComponent(txtpublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updatebookpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbtnsupplier)
                    .addComponent(txtsupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updatebookpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbtnauthor)
                    .addComponent(txtauthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updatebookpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbtnbookcover)
                    .addComponent(txtbookcover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updatebookpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbtntype)
                    .addComponent(txttype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updatebookpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbtnedition)
                    .addComponent(txtedition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        updatebookpane3.setBackground(new java.awt.Color(255, 255, 255));

        rdbtndescription.setForeground(new java.awt.Color(0, 0, 0));
        rdbtndescription.setText("Description");
        rdbtndescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtndescriptionActionPerformed(evt);
            }
        });

        txtdescription.setColumns(20);
        txtdescription.setLineWrap(true);
        txtdescription.setRows(5);
        txtdescription.setEnabled(false);
        jScrollPane1.setViewportView(txtdescription);

        btnupdate.setBackground(new java.awt.Color(0, 153, 255));
        btnupdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(255, 255, 255));
        btnupdate.setText("Update Book");
        btnupdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updatebookpane3Layout = new javax.swing.GroupLayout(updatebookpane3);
        updatebookpane3.setLayout(updatebookpane3Layout);
        updatebookpane3Layout.setHorizontalGroup(
            updatebookpane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatebookpane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updatebookpane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updatebookpane3Layout.createSequentialGroup()
                        .addComponent(rdbtndescription)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updatebookpane3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        updatebookpane3Layout.setVerticalGroup(
            updatebookpane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatebookpane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updatebookpane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbtndescription))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnupdate)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updatebookpane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(updatebookpane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(updatebookpane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(updatebookpane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updatebookpane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatebookpane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 897, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbtnnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnnameActionPerformed
        // TODO add your handling code here:
        if(txtname.isEnabled()){
            txtname.setEnabled(false);
        } else{
            txtname.setEnabled(true);
        }
    }//GEN-LAST:event_rdbtnnameActionPerformed

    private void rdbtnamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnamountActionPerformed
        // TODO add your handling code here:
        if(txtamount.isEnabled()){
            txtamount.setEnabled(false);
        } else{
            txtamount.setEnabled(true);
        }
    }//GEN-LAST:event_rdbtnamountActionPerformed

    private void rdbtnreleasedateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnreleasedateActionPerformed
        // TODO add your handling code here:
        if(txtreleasedate.isEnabled()){
            txtreleasedate.setEnabled(false);
        } else{
            txtreleasedate.setEnabled(true);
        }
    }//GEN-LAST:event_rdbtnreleasedateActionPerformed

    private void rdbtnnumpagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnnumpagesActionPerformed
        // TODO add your handling code here:
        if(txtnumpages.isEnabled()){
            txtnumpages.setEnabled(false);
        } else{
            txtnumpages.setEnabled(true);
        }
    }//GEN-LAST:event_rdbtnnumpagesActionPerformed

    private void rdbtnpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnpriceActionPerformed
        // TODO add your handling code here:
        if(txtprice.isEnabled()){
            txtprice.setEnabled(false);
        } else{
            txtprice.setEnabled(true);
        }
    }//GEN-LAST:event_rdbtnpriceActionPerformed

    private void txtidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtidFocusGained
        // TODO add your handling code here:
        if (txtid.getText().equals("Enter ID")) {
            txtid.setText("");
            txtid.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtidFocusGained

    private void txtidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtidFocusLost
        // TODO add your handling code here:
        if (txtid.getText().equals("")) {
            txtid.setText("Enter ID");
            txtid.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtidFocusLost

    private void txtnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnameFocusGained
        // TODO add your handling code here:
        if (txtname.getText().equals("Enter Name")) {
            txtname.setText("");
            txtname.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtnameFocusGained

    private void txtnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnameFocusLost
        // TODO add your handling code here:
        if (txtname.getText().equals("")) {
            txtname.setText("Enter Name");
            txtname.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtnameFocusLost

    private void txtamountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtamountFocusGained
        // TODO add your handling code here:
        if (txtamount.getText().equals("Enter Amount")) {
            txtamount.setText("");
            txtamount.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtamountFocusGained

    private void txtamountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtamountFocusLost
        // TODO add your handling code here:
        if (txtamount.getText().equals("")) {
            txtamount.setText("Enter Amount");
            txtamount.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtamountFocusLost

    private void txtreleasedateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtreleasedateFocusGained
        // TODO add your handling code here:
        if (txtreleasedate.getText().equals("Enter ReleaseDate")) {
            txtreleasedate.setText("");
            txtreleasedate.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtreleasedateFocusGained

    private void txtreleasedateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtreleasedateFocusLost
        // TODO add your handling code here:
        if (txtreleasedate.getText().equals("")) {
            txtreleasedate.setText("Enter ReleaseDate");
            txtreleasedate.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtreleasedateFocusLost

    private void txtnumpagesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnumpagesFocusGained
        // TODO add your handling code here:
        if (txtnumpages.getText().equals("Enter NumPages")) {
            txtnumpages.setText("");
            txtnumpages.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtnumpagesFocusGained

    private void txtnumpagesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnumpagesFocusLost
        // TODO add your handling code here:
        if (txtnumpages.getText().equals("")) {
            txtnumpages.setText("Enter NumPages");
            txtnumpages.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtnumpagesFocusLost

    private void txtpriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpriceFocusGained
        // TODO add your handling code here:
        if (txtprice.getText().equals("Enter Price")) {
            txtprice.setText("");
            txtprice.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtpriceFocusGained

    private void txtpriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpriceFocusLost
        // TODO add your handling code here:
        if (txtprice.getText().equals("")) {
            txtprice.setText("Enter Price");
            txtprice.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtpriceFocusLost

    private void rdbtnpublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnpublisherActionPerformed
        // TODO add your handling code here:
        if(txtpublisher.isEnabled()){
            txtpublisher.setEnabled(false);
        } else{
            txtpublisher.setEnabled(true);
        }
    }//GEN-LAST:event_rdbtnpublisherActionPerformed

    private void rdbtnsupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnsupplierActionPerformed
        // TODO add your handling code here:
        if(txtsupplier.isEnabled()){
            txtsupplier.setEnabled(false);
        } else{
            txtsupplier.setEnabled(true);
        }
    }//GEN-LAST:event_rdbtnsupplierActionPerformed

    private void rdbtnauthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnauthorActionPerformed
        // TODO add your handling code here:
        if(txtauthor.isEnabled()){
            txtauthor.setEnabled(false);
        } else{
            txtauthor.setEnabled(true);
        }
    }//GEN-LAST:event_rdbtnauthorActionPerformed

    private void rdbtnbookcoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnbookcoverActionPerformed
        // TODO add your handling code here:
        if(txtbookcover.isEnabled()){
            txtbookcover.setEnabled(false);
        } else{
            txtbookcover.setEnabled(true);
        }
    }//GEN-LAST:event_rdbtnbookcoverActionPerformed

    private void rdbtntypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtntypeActionPerformed
        // TODO add your handling code here:
        if(txttype.isEnabled()){
            txttype.setEnabled(false);
        } else{
            txttype.setEnabled(true);
        }
    }//GEN-LAST:event_rdbtntypeActionPerformed

    private void rdbtndescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtndescriptionActionPerformed
        // TODO add your handling code here:
        if(txtdescription.isEnabled()){
            txtdescription.setEnabled(false);
        } else{
            txtdescription.setEnabled(true);
        }
    }//GEN-LAST:event_rdbtndescriptionActionPerformed

    private void txtpublisherFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpublisherFocusGained
        // TODO add your handling code here:
        if (txtpublisher.getText().equals("Enter Publisher")) {
            txtpublisher.setText("");
            txtpublisher.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtpublisherFocusGained

    private void txtpublisherFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpublisherFocusLost
        // TODO add your handling code here:
        if (txtpublisher.getText().equals("")) {
            txtpublisher.setText("Enter Publisher");
            txtpublisher.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtpublisherFocusLost

    private void txtsupplierFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsupplierFocusGained
        // TODO add your handling code here:
        if (txtsupplier.getText().equals("Enter Supplier")) {
            txtsupplier.setText("");
            txtsupplier.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtsupplierFocusGained

    private void txtsupplierFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsupplierFocusLost
        // TODO add your handling code here:
        if (txtsupplier.getText().equals("")) {
            txtsupplier.setText("Enter Supplier");
            txtsupplier.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtsupplierFocusLost

    private void txtauthorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtauthorFocusGained
        // TODO add your handling code here:
        if (txtauthor.getText().equals("Enter Author")) {
            txtauthor.setText("");
            txtauthor.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtauthorFocusGained

    private void txtauthorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtauthorFocusLost
        // TODO add your handling code here:
        if (txtauthor.getText().equals("")) {
            txtauthor.setText("Enter Author");
            txtauthor.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtauthorFocusLost

    private void txtbookcoverFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtbookcoverFocusGained
        // TODO add your handling code here:
        if (txtbookcover.getText().equals("Enter BookCover")) {
            txtbookcover.setText("");
            txtbookcover.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtbookcoverFocusGained

    private void txtbookcoverFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtbookcoverFocusLost
        // TODO add your handling code here:
        if (txtbookcover.getText().equals("")) {
            txtbookcover.setText("Enter BookCover");
            txtbookcover.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtbookcoverFocusLost

    private void txttypeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttypeFocusGained
        // TODO add your handling code here:
        if (txttype.getText().equals("Enter Type")) {
            txttype.setText("");
            txttype.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txttypeFocusGained

    private void txttypeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttypeFocusLost
        // TODO add your handling code here:
        if (txttype.getText().equals("")) {
            txttype.setText("Enter Type");
            txttype.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txttypeFocusLost

    private void UpdateChoice(){
        if (rdbtnname.isSelected()) {
            this.bk.setName(txtname.getText());
        }
        if (rdbtnamount.isSelected()) {
            this.bk.setAmount(Integer.valueOf(txtamount.getText()));
        }
        if (rdbtnreleasedate.isSelected()) {
            this.bk.setReleaseDate(txtreleasedate.getText());
        }
        if (rdbtnnumpages.isSelected()) {
            this.bk.setNumPages(Integer.valueOf(txtnumpages.getText()));
        }
        if (rdbtnprice.isSelected()) {
            this.bk.setPrice(Double.valueOf(txtprice.getText()));
        }
        if (rdbtnpublisher.isSelected()) {
            this.bk.setPublisher(txtpublisher.getText());
        }
        if (rdbtnsupplier.isSelected()) {
            this.bk.setSupplier(txtsupplier.getText());
        }
        if (rdbtnauthor.isSelected()) {
            this.bk.setAuthor(txtauthor.getText());
        }
        if (rdbtnbookcover.isSelected()) {
            this.bk.setBookCover(txtbookcover.getText());
        }
        if (rdbtntype.isSelected()) {
            this.bk.setType(txttype.getText());
        }
        if (rdbtndescription.isSelected()) {
            this.bk.setDescription(txtdescription.getText());
        }
        if (rdbtnedition.isSelected()) {
            this.bk.setDescription(txtedition.getText());
        }
    }
    
    
    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        
        BookDao bkd = new BookDao();
        UpdateChoice();
        bkd.update(this.bk);
        this.dispose();
    }//GEN-LAST:event_btnupdateActionPerformed

    private void rdbtneditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtneditionActionPerformed
        // TODO add your handling code here:
        if(txtedition.isEnabled()){
            txtedition.setEnabled(false);
        } else{
            txtedition.setEnabled(true);
        }
    }//GEN-LAST:event_rdbtneditionActionPerformed

    private void txteditionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txteditionFocusGained
        // TODO add your handling code here:
        if (txttype.getText().equals("Enter Edition")) {
            txttype.setText("");
            txttype.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txteditionFocusGained

    private void txteditionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txteditionFocusLost
        // TODO add your handling code here:
        if (txttype.getText().equals("")) {
            txttype.setText("Enter Edition");
            txttype.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txteditionFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateBook dialog = new UpdateBook(new javax.swing.JFrame(), new Book());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdbtnamount;
    private javax.swing.JRadioButton rdbtnauthor;
    private javax.swing.JRadioButton rdbtnbookcover;
    private javax.swing.JRadioButton rdbtndescription;
    private javax.swing.JRadioButton rdbtnedition;
    private javax.swing.JRadioButton rdbtnname;
    private javax.swing.JRadioButton rdbtnnumpages;
    private javax.swing.JRadioButton rdbtnprice;
    private javax.swing.JRadioButton rdbtnpublisher;
    private javax.swing.JRadioButton rdbtnreleasedate;
    private javax.swing.JRadioButton rdbtnsupplier;
    private javax.swing.JRadioButton rdbtntype;
    private javax.swing.JTextField txtamount;
    private javax.swing.JTextField txtauthor;
    private javax.swing.JTextField txtbookcover;
    private javax.swing.JTextArea txtdescription;
    private javax.swing.JTextField txtedition;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnumpages;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtpublisher;
    private javax.swing.JTextField txtreleasedate;
    private javax.swing.JTextField txtsupplier;
    private javax.swing.JTextField txttype;
    private javax.swing.JPanel updatebookpane1;
    private javax.swing.JPanel updatebookpane2;
    private javax.swing.JPanel updatebookpane3;
    // End of variables declaration//GEN-END:variables
}
